# https://aka.ms/yaml


jobs:
  - job: 'Build_MacOS_HTTP'
    pool:
      vmImage: 'macOS-10.15'

    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          project: '4b438742-da7e-4123-8cf4-55564485db7e'
          pipeline: 6

          buildType: 'specific'
          buildVersionToDownload: 'latestFromBranch'
          branchName: "refs/heads/macos_obs_26.to.27"
          artifactName: obs_deps_macos
          targetPath: $(Build.SourcesDirectory)/CI/http/obs_deps/

      - script: $(Build.SourcesDirectory)/CI/http/install-script-osx.sh
        workingDirectory: $(Build.SourcesDirectory)/CI/http/
        displayName: 'Setup build'
        env:
          GOOGLE_API_KEY: $(GOOGLE_API_KEY)

      - task: PublishPipelineArtifact@1
        inputs:
          path: "$(Build.SourcesDirectory)/CI/http/release/"
          artifact: Closed_Captions_Plugin__Release_MacOS_HTTP

  - job: 'Build_Windows_HTTP'
    pool:
      vmImage: 'windows-2019'

    steps:
      - script: git submodule update --init --recursive
        displayName: 'Checkout Submodules'

      - task: DownloadPipelineArtifact@2
        inputs:
          project: '4b438742-da7e-4123-8cf4-55564485db7e'
          pipeline: 6

          buildType: 'specific'
          buildVersionToDownload: 'latestFromBranch'
          branchName: "refs/heads/windows_obs_26.to.27"
          artifactName: obs_deps_windows
          targetPath: $(Build.SourcesDirectory)/CI/http/obs_deps/

      - script: $(Build.SourcesDirectory)\CI\http\install-script-win.cmd
        displayName: 'Setup, CMake'
        workingDirectory: $(Build.SourcesDirectory)\CI\http
        env:
          GOOGLE_API_KEY: $(GOOGLE_API_KEY)

      - task: PublishPipelineArtifact@1
        inputs:
          path: '$(Build.SourcesDirectory)/CI/http/release/'
          artifact: Closed_Captions_Plugin__Release_Windows_HTTP

  - job: 'Build_Linux_HTTP'
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          project: '4b438742-da7e-4123-8cf4-55564485db7e'
          pipeline: 6

          buildType: 'specific'
          buildVersionToDownload: 'latestFromBranch'
          branchName: "refs/heads/linux_obs_26.to.27"
          artifactName: obs_deps_linux
          targetPath: $(Build.SourcesDirectory)/CI/http/obs_deps/

      - script: $(Build.SourcesDirectory)/CI/http/install-script-linux.sh
        displayName: 'Setup, CMake'
        workingDirectory: $(Build.SourcesDirectory)/CI/http/
        env:
          GOOGLE_API_KEY: $(GOOGLE_API_KEY)

      - task: PublishPipelineArtifact@1
        inputs:
          path: "$(Build.SourcesDirectory)/CI/http/release/"
          artifact: Closed_Captions_Plugin__Release_Linux64_HTTP

